# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from dnbr_severity_tasks import combine_severity_layers as combine_severity_layers
from dnbr_severity_tasks import compute_dnbr_severity as compute_dnbr_severity
from dnbr_severity_tasks import count_burned_area_ha as count_burned_area_ha
from dnbr_severity_tasks import (
    count_high_severity_area_ha as count_high_severity_area_ha,
)
from dnbr_severity_tasks import count_mean_dnbr as count_mean_dnbr
from dnbr_severity_tasks import count_post_images as count_post_images
from dnbr_severity_tasks import count_pre_images as count_pre_images
from dnbr_severity_tasks import create_dnbr_severity_layer as create_dnbr_severity_layer
from dnbr_severity_tasks import (
    create_styled_overlay_layer as create_styled_overlay_layer,
)
from dnbr_severity_tasks import format_area_ha as format_area_ha
from dnbr_severity_tasks import format_image_count as format_image_count
from dnbr_severity_tasks import format_mean_dnbr as format_mean_dnbr
from dnbr_severity_tasks import format_percent_burned as format_percent_burned
from dnbr_severity_tasks import get_aoi_area_ha as get_aoi_area_ha
from dnbr_severity_tasks import get_percent_burned as get_percent_burned
from dnbr_severity_tasks import set_aoi_group_name as set_aoi_group_name
from dnbr_severity_tasks import set_overlay_group_name as set_overlay_group_name
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.io import (
    get_spatial_features_group as get_spatial_features_group,
)
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import set_gee_connection as set_gee_connection
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_text_widget_single_view as create_text_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import (
    any_dependency_is_empty_string as any_dependency_is_empty_string,
)
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_connection = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_connection")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_connection") or {}))
        .call()
    )

    gee_connection = (
        task(set_gee_connection)
        .validate()
        .set_task_instance_id("gee_connection")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("gee_connection") or {}))
        .call()
    )

    aoi_name = (
        task(set_aoi_group_name)
        .validate()
        .set_task_instance_id("aoi_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("aoi_name") or {}))
        .call()
    )

    aoi_features = (
        task(get_spatial_features_group)
        .validate()
        .set_task_instance_id("aoi_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_connection,
            spatial_features_group_name=aoi_name,
            **(params.get("aoi_features") or {}),
        )
        .call()
    )

    overlay_name = (
        task(set_overlay_group_name)
        .validate()
        .set_task_instance_id("overlay_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("overlay_name") or {}))
        .call()
    )

    overlay_features = (
        task(get_spatial_features_group)
        .validate()
        .set_task_instance_id("overlay_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_is_empty_string,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_connection,
            spatial_features_group_name=overlay_name,
            **(params.get("overlay_features") or {}),
        )
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    severity_result = (
        task(compute_dnbr_severity)
        .validate()
        .set_task_instance_id("severity_result")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_connection,
            aoi=aoi_features,
            **(params.get("severity_result") or {}),
        )
        .call()
    )

    severity_layer = (
        task(create_dnbr_severity_layer)
        .validate()
        .set_task_instance_id("severity_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=severity_result, **(params.get("severity_layer") or {}))
        .call()
    )

    aoi_layer = (
        task(create_styled_overlay_layer)
        .validate()
        .set_task_instance_id("aoi_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=aoi_features, zoom=True, **(params.get("aoi_layer") or {})
        )
        .call()
    )

    overlay_layer = (
        task(create_styled_overlay_layer)
        .validate()
        .set_task_instance_id("overlay_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=overlay_features,
            zoom=False,
            **(params.get("overlay_layer") or {}),
        )
        .call()
    )

    combined_layers = (
        task(combine_severity_layers)
        .validate()
        .set_task_instance_id("combined_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            severity_layer=severity_layer,
            aoi_layer=aoi_layer,
            overlay_layer=overlay_layer,
            **(params.get("combined_layers") or {}),
        )
        .call()
    )

    severity_map = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("severity_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_maps,
            geo_layers=combined_layers,
            north_arrow_style={"placement": "top-left"},
            legend_style={"title": "Burn Severity", "placement": "bottom-right"},
            static=False,
            max_zoom=20,
            **(params.get("severity_map") or {}),
        )
        .call()
    )

    severity_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("severity_map_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="dnbr_severity",
            text=severity_map,
            **(params.get("severity_map_url") or {}),
        )
        .call()
    )

    map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Burn Severity Map",
            data=severity_map_url,
            **(params.get("map_widget") or {}),
        )
        .call()
    )

    severity_file = (
        task(persist_df)
        .validate()
        .set_task_instance_id("severity_file")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=severity_result,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="geojson",
            **(params.get("severity_file") or {}),
        )
        .call()
    )

    burned_area_ha = (
        task(count_burned_area_ha)
        .validate()
        .set_task_instance_id("burned_area_ha")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=severity_result, **(params.get("burned_area_ha") or {}))
        .call()
    )

    burned_area_fmt = (
        task(format_area_ha)
        .validate()
        .set_task_instance_id("burned_area_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(area_ha=burned_area_ha, **(params.get("burned_area_fmt") or {}))
        .call()
    )

    widget_burned = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_burned")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Burned", data=burned_area_fmt, **(params.get("widget_burned") or {})
        )
        .call()
    )

    high_severity_ha = (
        task(count_high_severity_area_ha)
        .validate()
        .set_task_instance_id("high_severity_ha")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=severity_result, **(params.get("high_severity_ha") or {}))
        .call()
    )

    high_severity_fmt = (
        task(format_area_ha)
        .validate()
        .set_task_instance_id("high_severity_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(area_ha=high_severity_ha, **(params.get("high_severity_fmt") or {}))
        .call()
    )

    widget_high_severity = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_high_severity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="High Sev",
            data=high_severity_fmt,
            **(params.get("widget_high_severity") or {}),
        )
        .call()
    )

    aoi_area_result = (
        task(get_aoi_area_ha)
        .validate()
        .set_task_instance_id("aoi_area_result")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=severity_result, **(params.get("aoi_area_result") or {}))
        .call()
    )

    percent_burned = (
        task(get_percent_burned)
        .validate()
        .set_task_instance_id("percent_burned")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            burned_ha=burned_area_ha,
            aoi_area_ha=aoi_area_result,
            **(params.get("percent_burned") or {}),
        )
        .call()
    )

    percent_burned_fmt = (
        task(format_percent_burned)
        .validate()
        .set_task_instance_id("percent_burned_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(percent=percent_burned, **(params.get("percent_burned_fmt") or {}))
        .call()
    )

    widget_percent_burned = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_percent_burned")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="% Burned",
            data=percent_burned_fmt,
            **(params.get("widget_percent_burned") or {}),
        )
        .call()
    )

    mean_dnbr = (
        task(count_mean_dnbr)
        .validate()
        .set_task_instance_id("mean_dnbr")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=severity_result, **(params.get("mean_dnbr") or {}))
        .call()
    )

    mean_dnbr_fmt = (
        task(format_mean_dnbr)
        .validate()
        .set_task_instance_id("mean_dnbr_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(dnbr_value=mean_dnbr, **(params.get("mean_dnbr_fmt") or {}))
        .call()
    )

    widget_mean_dnbr = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_mean_dnbr")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mean dNBR",
            data=mean_dnbr_fmt,
            **(params.get("widget_mean_dnbr") or {}),
        )
        .call()
    )

    pre_scenes = (
        task(count_pre_images)
        .validate()
        .set_task_instance_id("pre_scenes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=severity_result, **(params.get("pre_scenes") or {}))
        .call()
    )

    pre_scenes_fmt = (
        task(format_image_count)
        .validate()
        .set_task_instance_id("pre_scenes_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(count=pre_scenes, **(params.get("pre_scenes_fmt") or {}))
        .call()
    )

    widget_pre_scenes = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_pre_scenes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Pre Imgs",
            data=pre_scenes_fmt,
            **(params.get("widget_pre_scenes") or {}),
        )
        .call()
    )

    post_scenes = (
        task(count_post_images)
        .validate()
        .set_task_instance_id("post_scenes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=severity_result, **(params.get("post_scenes") or {}))
        .call()
    )

    post_scenes_fmt = (
        task(format_image_count)
        .validate()
        .set_task_instance_id("post_scenes_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(count=post_scenes, **(params.get("post_scenes_fmt") or {}))
        .call()
    )

    widget_post_scenes = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_post_scenes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Post Imgs",
            data=post_scenes_fmt,
            **(params.get("widget_post_scenes") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                widget_burned,
                widget_high_severity,
                widget_percent_burned,
                widget_mean_dnbr,
                widget_pre_scenes,
                widget_post_scenes,
                map_widget,
            ],
            time_range=None,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
